// CSS Validation Script
// Runs all tests (which populates the CSS collector) then validates
// each generated CSS string using css-tree.
//
// Usage: npm run validate

import * as csstree from 'css-tree';

// Importing Tests.js runs the full test suite.
// All test modules are loaded as dependencies, and their module-level
// code calls createFss/testCase/testEqual which populates collectedCss.
import './public/tests/Tests.js';
import { collectedCss } from './public/tests/Utils.js';

console.log('\n=== CSS Validation ===\n');

let validated = 0;
let skipped = 0;
let invalid = 0;
const failures = [];

for (const css of collectedCss) {
    // Skip non-CSS strings (e.g. combined classnames from the combine function)
    if (!css.includes('{')) {
        skipped++;
        continue;
    }

    // Wrap raw @keyframes content: animation strings like "animName{0%{...}}"
    // These are generated by createAnimation and need @keyframes to be valid CSS.
    let cssToValidate = css;
    if (/^\S+\{\d+%/.test(css)) {
        cssToValidate = '@keyframes ' + css;
    }

    const errors = [];
    csstree.parse(cssToValidate, {
        onParseError(error) {
            errors.push(error);
        }
    });

    validated++;
    if (errors.length > 0) {
        invalid++;
        const preview = css.length > 120 ? css.substring(0, 120) + '...' : css;
        failures.push({ css: preview, errors });
    }
}

if (failures.length > 0) {
    for (const { css, errors } of failures) {
        console.error(`INVALID: ${css}`);
        for (const err of errors) {
            console.error(`  ${err.message}`);
        }
        console.error('');
    }
}

console.log(`CSS strings validated: ${validated}, Skipped: ${skipped}`);
if (invalid > 0) {
    console.error(`Invalid: ${invalid}`);
    process.exit(1);
} else {
    console.log('All CSS is valid!');
}
