namespace Fss

[<AutoOpen>]
module Caret =
    let private caretColorToString (caretColor: Types.ICaretColor) =
        match caretColor with
        | :? Types.Color as c -> Types.colorHelpers.colorToString c
        | :? Types.Auto -> Types.masterTypeHelpers.auto
        | _ -> "Unknown caret color"

    // https://developer.mozilla.org/en-US/docs/Web/CSS/caret-color
    let private caretColorValue value = Types.propertyHelpers.cssValue Types.Property.CaretColor value
    let private caretColorValue' value =
        value
        |> caretColorToString
        |> caretColorValue
    type CaretColor =
        static member Value (color: Types.ICaretColor) = color |> caretColorValue'
        static member black = Types.Color.black |> caretColorValue'
        static member silver = Types.Color.silver |> caretColorValue'
        static member gray = Types.Color.gray |> caretColorValue'
        static member white = Types.Color.white |> caretColorValue'
        static member maroon = Types.Color.maroon |> caretColorValue'
        static member red = Types.Color.red |> caretColorValue'
        static member purple = Types.Color.purple |> caretColorValue'
        static member fuchsia = Types.Color.fuchsia |> caretColorValue'
        static member green = Types.Color.green |> caretColorValue'
        static member lime = Types.Color.lime |> caretColorValue'
        static member olive = Types.Color.olive |> caretColorValue'
        static member yellow = Types.Color.yellow |> caretColorValue'
        static member navy = Types.Color.navy |> caretColorValue'
        static member blue = Types.Color.blue |> caretColorValue'
        static member teal = Types.Color.teal |> caretColorValue'
        static member aqua = Types.Color.aqua |> caretColorValue'
        static member orange = Types.Color.orange |> caretColorValue'
        static member aliceBlue = Types.Color.aliceBlue |> caretColorValue'
        static member antiqueWhite = Types.Color.antiqueWhite |> caretColorValue'
        static member aquaMarine = Types.Color.aquaMarine |> caretColorValue'
        static member azure = Types.Color.azure |> caretColorValue'
        static member beige = Types.Color.beige |> caretColorValue'
        static member bisque = Types.Color.bisque |> caretColorValue'
        static member blanchedAlmond = Types.Color.blanchedAlmond |> caretColorValue'
        static member blueViolet = Types.Color.blueViolet |> caretColorValue'
        static member brown = Types.Color.brown |> caretColorValue'
        static member burlywood = Types.Color.burlywood |> caretColorValue'
        static member cadetBlue = Types.Color.cadetBlue |> caretColorValue'
        static member chartreuse = Types.Color.chartreuse |> caretColorValue'
        static member chocolate = Types.Color.chocolate |> caretColorValue'
        static member coral = Types.Color.coral |> caretColorValue'
        static member cornflowerBlue = Types.Color.cornflowerBlue |> caretColorValue'
        static member cornsilk = Types.Color.cornsilk |> caretColorValue'
        static member crimson = Types.Color.crimson |> caretColorValue'
        static member cyan = Types.Color.cyan |> caretColorValue'
        static member darkBlue = Types.Color.darkBlue |> caretColorValue'
        static member darkCyan = Types.Color.darkCyan |> caretColorValue'
        static member darkGoldenrod = Types.Color.darkGoldenrod |> caretColorValue'
        static member darkGray = Types.Color.darkGray |> caretColorValue'
        static member darkGreen = Types.Color.darkGreen |> caretColorValue'
        static member darkKhaki = Types.Color.darkKhaki |> caretColorValue'
        static member darkMagenta = Types.Color.darkMagenta |> caretColorValue'
        static member darkOliveGreen = Types.Color.darkOliveGreen |> caretColorValue'
        static member darkOrange = Types.Color.darkOrange |> caretColorValue'
        static member darkOrchid = Types.Color.darkOrchid |> caretColorValue'
        static member darkRed = Types.Color.darkRed |> caretColorValue'
        static member darkSalmon = Types.Color.darkSalmon |> caretColorValue'
        static member darkSeaGreen = Types.Color.darkSeaGreen |> caretColorValue'
        static member darkSlateBlue = Types.Color.darkSlateBlue |> caretColorValue'
        static member darkSlateGray = Types.Color.darkSlateGray |> caretColorValue'
        static member darkTurquoise = Types.Color.darkTurquoise |> caretColorValue'
        static member darkViolet = Types.Color.darkViolet |> caretColorValue'
        static member deepPink = Types.Color.deepPink |> caretColorValue'
        static member deepSkyBlue = Types.Color.deepSkyBlue |> caretColorValue'
        static member dimGrey = Types.Color.dimGrey |> caretColorValue'
        static member dodgerBlue = Types.Color.dodgerBlue |> caretColorValue'
        static member fireBrick = Types.Color.fireBrick |> caretColorValue'
        static member floralWhite = Types.Color.floralWhite |> caretColorValue'
        static member forestGreen = Types.Color.forestGreen |> caretColorValue'
        static member gainsboro = Types.Color.gainsboro |> caretColorValue'
        static member ghostWhite = Types.Color.ghostWhite |> caretColorValue'
        static member gold = Types.Color.gold |> caretColorValue'
        static member goldenrod = Types.Color.goldenrod |> caretColorValue'
        static member greenYellow = Types.Color.greenYellow |> caretColorValue'
        static member grey = Types.Color.grey |> caretColorValue'
        static member honeydew = Types.Color.honeydew |> caretColorValue'
        static member hotPink = Types.Color.hotPink |> caretColorValue'
        static member indianRed = Types.Color.indianRed |> caretColorValue'
        static member indigo = Types.Color.indigo |> caretColorValue'
        static member ivory = Types.Color.ivory |> caretColorValue'
        static member khaki = Types.Color.khaki |> caretColorValue'
        static member lavender = Types.Color.lavender |> caretColorValue'
        static member lavenderBlush = Types.Color.lavenderBlush |> caretColorValue'
        static member lawnGreen = Types.Color.lawnGreen |> caretColorValue'
        static member lemonChiffon = Types.Color.lemonChiffon |> caretColorValue'
        static member lightBlue = Types.Color.lightBlue |> caretColorValue'
        static member lightCoral = Types.Color.lightCoral |> caretColorValue'
        static member lightCyan = Types.Color.lightCyan |> caretColorValue'
        static member lightGoldenrodYellow = Types.Color.lightGoldenrodYellow |> caretColorValue'
        static member lightGray = Types.Color.lightGray |> caretColorValue'
        static member lightGreen = Types.Color.lightGreen |> caretColorValue'
        static member lightGrey = Types.Color.lightGrey |> caretColorValue'
        static member lightPink = Types.Color.lightPink |> caretColorValue'
        static member lightSalmon = Types.Color.lightSalmon |> caretColorValue'
        static member lightSeaGreen = Types.Color.lightSeaGreen |> caretColorValue'
        static member lightSkyBlue = Types.Color.lightSkyBlue |> caretColorValue'
        static member lightSlateGrey = Types.Color.lightSlateGrey |> caretColorValue'
        static member lightSteelBlue = Types.Color.lightSteelBlue |> caretColorValue'
        static member lightYellow = Types.Color.lightYellow |> caretColorValue'
        static member limeGreen = Types.Color.limeGreen |> caretColorValue'
        static member linen = Types.Color.linen |> caretColorValue'
        static member magenta = Types.Color.magenta |> caretColorValue'
        static member mediumAquamarine = Types.Color.mediumAquamarine |> caretColorValue'
        static member mediumBlue = Types.Color.mediumBlue |> caretColorValue'
        static member mediumOrchid = Types.Color.mediumOrchid |> caretColorValue'
        static member mediumPurple = Types.Color.mediumPurple |> caretColorValue'
        static member mediumSeaGreen = Types.Color.mediumSeaGreen |> caretColorValue'
        static member mediumSlateBlue = Types.Color.mediumSlateBlue |> caretColorValue'
        static member mediumSpringGreen = Types.Color.mediumSpringGreen |> caretColorValue'
        static member mediumTurquoise = Types.Color.mediumTurquoise |> caretColorValue'
        static member mediumVioletRed = Types.Color.mediumVioletRed |> caretColorValue'
        static member midnightBlue = Types.Color.midnightBlue |> caretColorValue'
        static member mintCream = Types.Color.mintCream |> caretColorValue'
        static member mistyRose = Types.Color.mistyRose |> caretColorValue'
        static member moccasin = Types.Color.moccasin |> caretColorValue'
        static member navajoWhite = Types.Color.navajoWhite |> caretColorValue'
        static member oldLace = Types.Color.oldLace |> caretColorValue'
        static member olivedrab = Types.Color.olivedrab |> caretColorValue'
        static member orangeRed = Types.Color.orangeRed |> caretColorValue'
        static member orchid = Types.Color.orchid |> caretColorValue'
        static member paleGoldenrod = Types.Color.paleGoldenrod |> caretColorValue'
        static member paleGreen = Types.Color.paleGreen |> caretColorValue'
        static member paleTurquoise = Types.Color.paleTurquoise |> caretColorValue'
        static member paleVioletred = Types.Color.paleVioletred |> caretColorValue'
        static member papayaWhip = Types.Color.papayaWhip |> caretColorValue'
        static member peachpuff = Types.Color.peachpuff |> caretColorValue'
        static member peru = Types.Color.peru |> caretColorValue'
        static member pink = Types.Color.pink |> caretColorValue'
        static member plum = Types.Color.plum |> caretColorValue'
        static member powderBlue = Types.Color.powderBlue |> caretColorValue'
        static member rosyBrown = Types.Color.rosyBrown |> caretColorValue'
        static member royalBlue = Types.Color.royalBlue |> caretColorValue'
        static member saddleBrown = Types.Color.saddleBrown |> caretColorValue'
        static member salmon = Types.Color.salmon |> caretColorValue'
        static member sandyBrown = Types.Color.sandyBrown |> caretColorValue'
        static member seaGreen = Types.Color.seaGreen |> caretColorValue'
        static member seaShell = Types.Color.seaShell |> caretColorValue'
        static member sienna = Types.Color.sienna |> caretColorValue'
        static member skyBlue = Types.Color.skyBlue |> caretColorValue'
        static member slateBlue = Types.Color.slateBlue |> caretColorValue'
        static member slateGray = Types.Color.slateGray |> caretColorValue'
        static member snow = Types.Color.snow |> caretColorValue'
        static member springGreen = Types.Color.springGreen |> caretColorValue'
        static member steelBlue = Types.Color.steelBlue |> caretColorValue'
        static member tan = Types.Color.tan |> caretColorValue'
        static member thistle = Types.Color.thistle |> caretColorValue'
        static member tomato = Types.Color.tomato |> caretColorValue'
        static member turquoise = Types.Color.turquoise |> caretColorValue'
        static member violet = Types.Color.violet |> caretColorValue'
        static member wheat = Types.Color.wheat |> caretColorValue'
        static member whiteSmoke = Types.Color.whiteSmoke |> caretColorValue'
        static member yellowGreen = Types.Color.yellowGreen |> caretColorValue'
        static member rebeccaPurple = Types.Color.rebeccaPurple |> caretColorValue'
        static member Rgb r g b = Types.Color.Rgb(r, g, b) |> caretColorValue'
        static member Rgba r g b a = Types.Color.Rgba(r, g, b, a) |> caretColorValue'
        static member Hex value = Types.Color.Hex value |> caretColorValue'
        static member Hsl h s l = Types.Color.Hsl(h, s, l) |> caretColorValue'
        static member Hsla h s l a  = Types.Color.Hsla (h, s, l, a) |> caretColorValue'
        static member transparent = Types.Color.transparent |> caretColorValue'
        static member currentColor = Types.Color.currentColor |> caretColorValue'

        static member Auto = Types.Auto |> caretColorValue'

    /// <summary>Specifies caret color.</summary>
    /// <param name="caretColor">
    ///     can be:
    ///     - <c> Types.Color </c>
    ///     - <c> Auto </c>
    /// </param>
    /// <returns>Css property for fss.</returns>
    let CaretColor' (caretColor: Types.ICaretColor) = CaretColor.Value caretColor
