namespace Fss

namespace Fss.FssTypes
    [<RequireQualifiedAccess>]
    module Appearance =
        type Appearance =
            | PushButton
            | SquareButton
            | Button
            | ButtonBevel
            | Listbox
            | Listitem
            | Menulist
            | MenulistButton
            | MenulistText
            | MenulistTextfield
            | Menupopup
            | ScrollbarbuttonUp
            | ScrollbarbuttonDown
            | ScrollbarbuttonLeft
            | ScrollbarbuttonRight
            | ScrollbartrackHorizontal
            | ScrollbartrackVertical
            | ScrollbarthumbHorizontal
            | ScrollbarthumbVertical
            | ScrollbargripperHorizontal
            | ScrollbargripperVertical
            | SliderHorizontal
            | SliderVertical
            | SliderthumbHorizontal
            | SliderthumbVertical
            | Caret
            | Searchfield
            | SearchfieldDecoration
            | SearchfieldResultsDecoration
            | SearchfieldResultsButton
            | SearchfieldCancelButton
            | Textfield
            | Textarea
            | Checkbox
            | CheckboxContainer
            | CheckboxSmall
            | Dialog
            | Menuitem
            | Progressbar
            | Radio
            | RadioContainer
            | RadioSmall
            | Resizer
            | Scrollbar
            | Separator
            | Statusbar
            | Tab
            | Tabpanels
            | TextfieldMultiline
            | Toolbar
            | Toolbarbutton
            | Toolbox
            | MozMacUnifiedToolbar
            | MozWinBorderlessGlass
            | MozWinBrowsertabbarToolbox
            | MozWinCommunicationsToolbox
            | MozWinGlass
            | MozWinMediaToolbox
            | Tooltip
            | Treeheadercell
            | Treeheadersortarrow
            | Treeitem
            | Treetwisty
            | Treetwistyopen
            | Treeview
            | Window
            interface IAppearance

