namespace Fss

namespace Fss.FssTypes

    [<AutoOpen>]
    module Color =
        type ColorType =
            | ColorType of string
            interface ITextDecorationColor
            interface ITextEmphasisColor
            interface IBorderColor
            interface IOutlineColor
            interface IColumnRuleColor
            interface ICaretColor
            interface IColorStop
            interface IColor
            interface IBackgroundColor

        type ColorTypeBase (valueFunction: string -> ColorType) =
            member this.black = Fss.Utilities.Color.hex "000000" |> valueFunction
            member this.silver = Fss.Utilities.Color.hex "c0c0c0" |> valueFunction
            member this.gray = Fss.Utilities.Color.hex "808080" |> valueFunction
            member this.white = Fss.Utilities.Color.hex "ffffff" |> valueFunction
            member this.maroon = Fss.Utilities.Color.hex "800000" |> valueFunction
            member this.red = Fss.Utilities.Color.hex "ff0000" |> valueFunction
            member this.purple = Fss.Utilities.Color.hex "800080" |> valueFunction
            member this.fuchsia = Fss.Utilities.Color.hex "ff00ff" |> valueFunction
            member this.green = Fss.Utilities.Color.hex "008000" |> valueFunction
            member this.lime = Fss.Utilities.Color.hex "00ff00" |> valueFunction
            member this.olive = Fss.Utilities.Color.hex "808000" |> valueFunction
            member this.yellow = Fss.Utilities.Color.hex "ffff00" |> valueFunction
            member this.navy = Fss.Utilities.Color.hex "000080" |> valueFunction
            member this.blue = Fss.Utilities.Color.hex "0000ff" |> valueFunction
            member this.teal = Fss.Utilities.Color.hex "008080" |> valueFunction
            member this.aqua = Fss.Utilities.Color.hex "00ffff" |> valueFunction
            member this.orange = Fss.Utilities.Color.hex "ffa500" |> valueFunction
            member this.aliceBlue = Fss.Utilities.Color.hex "f0f8ff" |> valueFunction
            member this.antiqueWhite = Fss.Utilities.Color.hex "faebd7" |> valueFunction
            member this.aquaMarine = Fss.Utilities.Color.hex "7fffd4" |> valueFunction
            member this.azure = Fss.Utilities.Color.hex "f0ffff" |> valueFunction
            member this.beige = Fss.Utilities.Color.hex "f5f5dc" |> valueFunction
            member this.bisque = Fss.Utilities.Color.hex "ffe4c4" |> valueFunction
            member this.blanchedAlmond = Fss.Utilities.Color.hex "ffebcd" |> valueFunction
            member this.blueViolet = Fss.Utilities.Color.hex "8a2be2" |> valueFunction
            member this.brown = Fss.Utilities.Color.hex "a52a2a" |> valueFunction
            member this.burlywood = Fss.Utilities.Color.hex "deb887" |> valueFunction
            member this.cadetBlue = Fss.Utilities.Color.hex "5f9ea0" |> valueFunction
            member this.chartreuse = Fss.Utilities.Color.hex "7fff00" |> valueFunction
            member this.chocolate = Fss.Utilities.Color.hex "d2691e" |> valueFunction
            member this.coral = Fss.Utilities.Color.hex "ff7f50" |> valueFunction
            member this.cornflowerBlue = Fss.Utilities.Color.hex "6495ed" |> valueFunction
            member this.cornsilk = Fss.Utilities.Color.hex "fff8dc" |> valueFunction
            member this.crimson = Fss.Utilities.Color.hex "dc143c" |> valueFunction
            member this.cyan = Fss.Utilities.Color.hex "00ffff" |> valueFunction
            member this.darkBlue = Fss.Utilities.Color.hex "00008b" |> valueFunction
            member this.darkCyan = Fss.Utilities.Color.hex "008b8b" |> valueFunction
            member this.darkGoldenrod = Fss.Utilities.Color.hex "b8860b" |> valueFunction
            member this.darkGray = Fss.Utilities.Color.hex "a9a9a9" |> valueFunction
            member this.darkGreen = Fss.Utilities.Color.hex "006400" |> valueFunction
            member this.darkKhaki = Fss.Utilities.Color.hex "bdb76b" |> valueFunction
            member this.darkMagenta = Fss.Utilities.Color.hex "8b008b" |> valueFunction
            member this.darkOliveGreen = Fss.Utilities.Color.hex "556b2f" |> valueFunction
            member this.darkOrange = Fss.Utilities.Color.hex "ff8c00" |> valueFunction
            member this.darkOrchid = Fss.Utilities.Color.hex "9932cc" |> valueFunction
            member this.darkRed = Fss.Utilities.Color.hex "8b0000" |> valueFunction
            member this.darkSalmon = Fss.Utilities.Color.hex "e9967a" |> valueFunction
            member this.darkSeaGreen = Fss.Utilities.Color.hex "8fbc8f" |> valueFunction
            member this.darkSlateBlue = Fss.Utilities.Color.hex "483d8b" |> valueFunction
            member this.darkSlateGray = Fss.Utilities.Color.hex "2f4f4f" |> valueFunction
            member this.darkTurquoise = Fss.Utilities.Color.hex "00ced1" |> valueFunction
            member this.darkViolet = Fss.Utilities.Color.hex "9400d3" |> valueFunction
            member this.deepPink = Fss.Utilities.Color.hex "ff1493" |> valueFunction
            member this.deepSkyBlue = Fss.Utilities.Color.hex "00bfff" |> valueFunction
            member this.dimGrey = Fss.Utilities.Color.hex "696969" |> valueFunction
            member this.dodgerBlue = Fss.Utilities.Color.hex "1e90ff" |> valueFunction
            member this.fireBrick = Fss.Utilities.Color.hex "b22222" |> valueFunction
            member this.floralWhite = Fss.Utilities.Color.hex "fffaf0" |> valueFunction
            member this.forestGreen = Fss.Utilities.Color.hex "228b22" |> valueFunction
            member this.gainsboro = Fss.Utilities.Color.hex "dcdcdc" |> valueFunction
            member this.ghostWhite = Fss.Utilities.Color.hex "f8f8ff" |> valueFunction
            member this.gold = Fss.Utilities.Color.hex "ffd700" |> valueFunction
            member this.goldenrod = Fss.Utilities.Color.hex "daa520" |> valueFunction
            member this.greenYellow = Fss.Utilities.Color.hex "adff2f" |> valueFunction
            member this.grey = Fss.Utilities.Color.hex "808080" |> valueFunction
            member this.honeydew = Fss.Utilities.Color.hex "f0fff0" |> valueFunction
            member this.hotPink = Fss.Utilities.Color.hex "ff69b4" |> valueFunction
            member this.indianRed = Fss.Utilities.Color.hex "cd5c5c" |> valueFunction
            member this.indigo = Fss.Utilities.Color.hex "4b0082" |> valueFunction
            member this.ivory = Fss.Utilities.Color.hex "fffff0" |> valueFunction
            member this.khaki = Fss.Utilities.Color.hex "f0e68c" |> valueFunction
            member this.lavender = Fss.Utilities.Color.hex "e6e6fa" |> valueFunction
            member this.lavenderBlush = Fss.Utilities.Color.hex "fff0f5" |> valueFunction
            member this.lawnGreen = Fss.Utilities.Color.hex "7cfc00" |> valueFunction
            member this.lemonChiffon = Fss.Utilities.Color.hex "fffacd" |> valueFunction
            member this.lightBlue = Fss.Utilities.Color.hex "add8e6" |> valueFunction
            member this.lightCoral = Fss.Utilities.Color.hex "f08080" |> valueFunction
            member this.lightCyan = Fss.Utilities.Color.hex "e0ffff" |> valueFunction
            member this.lightGoldenrodYellow = Fss.Utilities.Color.hex "fafad2" |> valueFunction
            member this.lightGray = Fss.Utilities.Color.hex "d3d3d3" |> valueFunction
            member this.lightGreen = Fss.Utilities.Color.hex "90ee90" |> valueFunction
            member this.lightGrey = Fss.Utilities.Color.hex "d3d3d3" |> valueFunction
            member this.lightPink = Fss.Utilities.Color.hex "ffb6c1" |> valueFunction
            member this.lightSalmon = Fss.Utilities.Color.hex "ffa07a" |> valueFunction
            member this.lightSeaGreen = Fss.Utilities.Color.hex "20b2aa" |> valueFunction
            member this.lightSkyBlue = Fss.Utilities.Color.hex "87cefa" |> valueFunction
            member this.lightSlateGrey = Fss.Utilities.Color.hex "778899" |> valueFunction
            member this.lightSteelBlue = Fss.Utilities.Color.hex "b0c4de" |> valueFunction
            member this.lightYellow = Fss.Utilities.Color.hex "ffffe0" |> valueFunction
            member this.limeGreen = Fss.Utilities.Color.hex "32cd32" |> valueFunction
            member this.linen = Fss.Utilities.Color.hex "faf0e6" |> valueFunction
            member this.magenta = Fss.Utilities.Color.hex "ff00ff" |> valueFunction
            member this.mediumAquamarine = Fss.Utilities.Color.hex "66cdaa" |> valueFunction
            member this.mediumBlue = Fss.Utilities.Color.hex "0000cd" |> valueFunction
            member this.mediumOrchid = Fss.Utilities.Color.hex "ba55d3" |> valueFunction
            member this.mediumPurple = Fss.Utilities.Color.hex "9370db" |> valueFunction
            member this.mediumSeaGreen = Fss.Utilities.Color.hex "3cb371" |> valueFunction
            member this.mediumSlateBlue = Fss.Utilities.Color.hex "7b68ee" |> valueFunction
            member this.mediumSpringGreen = Fss.Utilities.Color.hex "00fa9a" |> valueFunction
            member this.mediumTurquoise = Fss.Utilities.Color.hex "48d1cc" |> valueFunction
            member this.mediumVioletRed = Fss.Utilities.Color.hex "c71585" |> valueFunction
            member this.midnightBlue = Fss.Utilities.Color.hex "191970" |> valueFunction
            member this.mintCream = Fss.Utilities.Color.hex "f5fffa" |> valueFunction
            member this.mistyRose = Fss.Utilities.Color.hex "ffe4e1" |> valueFunction
            member this.moccasin = Fss.Utilities.Color.hex "ffe4b5" |> valueFunction
            member this.navajoWhite = Fss.Utilities.Color.hex "ffdead" |> valueFunction
            member this.oldLace = Fss.Utilities.Color.hex "fdf5e6" |> valueFunction
            member this.olivedrab = Fss.Utilities.Color.hex "6b8e23" |> valueFunction
            member this.orangeRed = Fss.Utilities.Color.hex "ff4500" |> valueFunction
            member this.orchid = Fss.Utilities.Color.hex "da70d6" |> valueFunction
            member this.paleGoldenrod = Fss.Utilities.Color.hex "eee8aa" |> valueFunction
            member this.paleGreen = Fss.Utilities.Color.hex "98fb98" |> valueFunction
            member this.paleTurquoise = Fss.Utilities.Color.hex "afeeee" |> valueFunction
            member this.paleVioletred = Fss.Utilities.Color.hex "db7093" |> valueFunction
            member this.papayaWhip = Fss.Utilities.Color.hex "ffefd5" |> valueFunction
            member this.peachpuff = Fss.Utilities.Color.hex "ffdab9" |> valueFunction
            member this.peru = Fss.Utilities.Color.hex "cd853f" |> valueFunction
            member this.pink = Fss.Utilities.Color.hex "ffc0cb" |> valueFunction
            member this.plum = Fss.Utilities.Color.hex "dda0dd" |> valueFunction
            member this.powderBlue = Fss.Utilities.Color.hex "b0e0e6" |> valueFunction
            member this.rosyBrown = Fss.Utilities.Color.hex "bc8f8f" |> valueFunction
            member this.royalBlue = Fss.Utilities.Color.hex "4169e1" |> valueFunction
            member this.saddleBrown = Fss.Utilities.Color.hex "8b4513" |> valueFunction
            member this.salmon = Fss.Utilities.Color.hex "fa8072" |> valueFunction
            member this.sandyBrown = Fss.Utilities.Color.hex "f4a460" |> valueFunction
            member this.seaGreen = Fss.Utilities.Color.hex "2e8b57" |> valueFunction
            member this.seaShell = Fss.Utilities.Color.hex "fff5ee" |> valueFunction
            member this.sienna = Fss.Utilities.Color.hex "a0522d" |> valueFunction
            member this.skyBlue = Fss.Utilities.Color.hex "87ceeb" |> valueFunction
            member this.slateBlue = Fss.Utilities.Color.hex "6a5acd" |> valueFunction
            member this.slateGray = Fss.Utilities.Color.hex "708090" |> valueFunction
            member this.snow = Fss.Utilities.Color.hex "fffafa" |> valueFunction
            member this.springGreen = Fss.Utilities.Color.hex "00ff7f" |> valueFunction
            member this.steelBlue = Fss.Utilities.Color.hex "4682b4" |> valueFunction
            member this.tan = Fss.Utilities.Color.hex "d2b48c" |> valueFunction
            member this.thistle = Fss.Utilities.Color.hex "d8bfd8" |> valueFunction
            member this.tomato = Fss.Utilities.Color.hex "ff6347" |> valueFunction
            member this.turquoise = Fss.Utilities.Color.hex "40e0d0" |> valueFunction
            member this.violet = Fss.Utilities.Color.hex "ee82ee" |> valueFunction
            member this.wheat = Fss.Utilities.Color.hex "f5deb3" |> valueFunction
            member this.whiteSmoke = Fss.Utilities.Color.hex "f5f5f5" |> valueFunction
            member this.yellowGreen = Fss.Utilities.Color.hex "9acd32" |> valueFunction
            member this.rebeccaPurple = Fss.Utilities.Color.hex "663399" |> valueFunction
            member this.transparent = Fss.Utilities.Color.rgba 0 0 0 0.0 |> valueFunction
            member this.currentColor = "currentColor" |> valueFunction
            member this.rgb (r: int, g: int, b: int) = Fss.Utilities.Color.rgb r g b |> valueFunction
            member this.rgba (r: int, g: int, b: int, a: float) = Fss.Utilities.Color.rgba r g b a |> valueFunction
            member this.hex (value: string) = Fss.Utilities.Color.hex value |> valueFunction
            member this.hsl (h: int, s: float, l: float) = Fss.Utilities.Color.hsl h s l |> valueFunction
            member this.hsla (h: int, s: float, l: float, a: float) = Fss.Utilities.Color.hsla h s l a |> valueFunction

        let Color = ColorTypeBase (ColorType)

        type ColorBase (valueFunction: ColorType -> CssProperty) =
            member this.black = Color.black |> valueFunction
            member this.silver = Color.silver |> valueFunction
            member this.gray = Color.gray |> valueFunction
            member this.white = Color.white |> valueFunction
            member this.maroon = Color.maroon |> valueFunction
            member this.red = Color.red |> valueFunction
            member this.purple = Color.purple |> valueFunction
            member this.fuchsia = Color.fuchsia |> valueFunction
            member this.green = Color.green |> valueFunction
            member this.lime = Color.lime |> valueFunction
            member this.olive = Color.olive |> valueFunction
            member this.yellow = Color.yellow |> valueFunction
            member this.navy = Color.navy |> valueFunction
            member this.blue = Color.blue |> valueFunction
            member this.teal = Color.teal |> valueFunction
            member this.aqua = Color.aqua |> valueFunction
            member this.orange = Color.orange |> valueFunction
            member this.aliceBlue = Color.aliceBlue |> valueFunction
            member this.antiqueWhite = Color.antiqueWhite |> valueFunction
            member this.aquaMarine = Color.aquaMarine |> valueFunction
            member this.azure = Color.azure |> valueFunction
            member this.beige = Color.beige |> valueFunction
            member this.bisque = Color.bisque |> valueFunction
            member this.blanchedAlmond = Color.blanchedAlmond |> valueFunction
            member this.blueViolet = Color.blueViolet |> valueFunction
            member this.brown = Color.brown |> valueFunction
            member this.burlywood = Color.burlywood |> valueFunction
            member this.cadetBlue = Color.cadetBlue |> valueFunction
            member this.chartreuse = Color.chartreuse |> valueFunction
            member this.chocolate = Color.chocolate |> valueFunction
            member this.coral = Color.coral |> valueFunction
            member this.cornflowerBlue = Color.cornflowerBlue |> valueFunction
            member this.cornsilk = Color.cornsilk |> valueFunction
            member this.crimson = Color.crimson |> valueFunction
            member this.cyan = Color.cyan |> valueFunction
            member this.darkBlue = Color.darkBlue |> valueFunction
            member this.darkCyan = Color.darkCyan |> valueFunction
            member this.darkGoldenrod = Color.darkGoldenrod |> valueFunction
            member this.darkGray = Color.darkGray |> valueFunction
            member this.darkGreen = Color.darkGreen |> valueFunction
            member this.darkKhaki = Color.darkKhaki |> valueFunction
            member this.darkMagenta = Color.darkMagenta |> valueFunction
            member this.darkOliveGreen = Color.darkOliveGreen |> valueFunction
            member this.darkOrange = Color.darkOrange |> valueFunction
            member this.darkOrchid = Color.darkOrchid |> valueFunction
            member this.darkRed = Color.darkRed |> valueFunction
            member this.darkSalmon = Color.darkSalmon |> valueFunction
            member this.darkSeaGreen = Color.darkSeaGreen |> valueFunction
            member this.darkSlateBlue = Color.darkSlateBlue |> valueFunction
            member this.darkSlateGray = Color.darkSlateGray |> valueFunction
            member this.darkTurquoise = Color.darkTurquoise |> valueFunction
            member this.darkViolet = Color.darkViolet |> valueFunction
            member this.deepPink = Color.deepPink |> valueFunction
            member this.deepSkyBlue = Color.deepSkyBlue |> valueFunction
            member this.dimGrey = Color.dimGrey |> valueFunction
            member this.dodgerBlue = Color.dodgerBlue |> valueFunction
            member this.fireBrick = Color.fireBrick |> valueFunction
            member this.floralWhite = Color.floralWhite |> valueFunction
            member this.forestGreen = Color.forestGreen |> valueFunction
            member this.gainsboro = Color.gainsboro |> valueFunction
            member this.ghostWhite = Color.ghostWhite |> valueFunction
            member this.gold = Color.gold |> valueFunction
            member this.goldenrod = Color.goldenrod |> valueFunction
            member this.greenYellow = Color.greenYellow |> valueFunction
            member this.grey = Color.grey |> valueFunction
            member this.honeydew = Color.honeydew |> valueFunction
            member this.hotPink = Color.hotPink |> valueFunction
            member this.indianRed = Color.indianRed |> valueFunction
            member this.indigo = Color.indigo |> valueFunction
            member this.ivory = Color.ivory |> valueFunction
            member this.khaki = Color.khaki |> valueFunction
            member this.lavender = Color.lavender |> valueFunction
            member this.lavenderBlush = Color.lavenderBlush |> valueFunction
            member this.lawnGreen = Color.lawnGreen |> valueFunction
            member this.lemonChiffon = Color.lemonChiffon |> valueFunction
            member this.lightBlue = Color.lightBlue |> valueFunction
            member this.lightCoral = Color.lightCoral |> valueFunction
            member this.lightCyan = Color.lightCyan |> valueFunction
            member this.lightGoldenrodYellow = Color.lightGoldenrodYellow |> valueFunction
            member this.lightGray = Color.lightGray |> valueFunction
            member this.lightGreen = Color.lightGreen |> valueFunction
            member this.lightGrey = Color.lightGrey |> valueFunction
            member this.lightPink = Color.lightPink |> valueFunction
            member this.lightSalmon = Color.lightSalmon |> valueFunction
            member this.lightSeaGreen = Color.lightSeaGreen |> valueFunction
            member this.lightSkyBlue = Color.lightSkyBlue |> valueFunction
            member this.lightSlateGrey = Color.lightSlateGrey |> valueFunction
            member this.lightSteelBlue = Color.lightSteelBlue |> valueFunction
            member this.lightYellow = Color.lightYellow |> valueFunction
            member this.limeGreen = Color.limeGreen |> valueFunction
            member this.linen = Color.linen |> valueFunction
            member this.magenta = Color.magenta |> valueFunction
            member this.mediumAquamarine = Color.mediumAquamarine |> valueFunction
            member this.mediumBlue = Color.mediumBlue |> valueFunction
            member this.mediumOrchid = Color.mediumOrchid |> valueFunction
            member this.mediumPurple = Color.mediumPurple |> valueFunction
            member this.mediumSeaGreen = Color.mediumSeaGreen |> valueFunction
            member this.mediumSlateBlue = Color.mediumSlateBlue |> valueFunction
            member this.mediumSpringGreen = Color.mediumSpringGreen |> valueFunction
            member this.mediumTurquoise = Color.mediumTurquoise |> valueFunction
            member this.mediumVioletRed = Color.mediumVioletRed |> valueFunction
            member this.midnightBlue = Color.midnightBlue |> valueFunction
            member this.mintCream = Color.mintCream |> valueFunction
            member this.mistyRose = Color.mistyRose |> valueFunction
            member this.moccasin = Color.moccasin |> valueFunction
            member this.navajoWhite = Color.navajoWhite |> valueFunction
            member this.oldLace = Color.oldLace |> valueFunction
            member this.olivedrab = Color.olivedrab |> valueFunction
            member this.orangeRed = Color.orangeRed |> valueFunction
            member this.orchid = Color.orchid |> valueFunction
            member this.paleGoldenrod = Color.paleGoldenrod |> valueFunction
            member this.paleGreen = Color.paleGreen |> valueFunction
            member this.paleTurquoise = Color.paleTurquoise |> valueFunction
            member this.paleVioletred = Color.paleVioletred |> valueFunction
            member this.papayaWhip = Color.papayaWhip |> valueFunction
            member this.peachpuff = Color.peachpuff |> valueFunction
            member this.peru = Color.peru |> valueFunction
            member this.pink = Color.pink |> valueFunction
            member this.plum = Color.plum |> valueFunction
            member this.powderBlue = Color.powderBlue |> valueFunction
            member this.rosyBrown = Color.rosyBrown |> valueFunction
            member this.royalBlue = Color.royalBlue |> valueFunction
            member this.saddleBrown = Color.saddleBrown |> valueFunction
            member this.salmon = Color.salmon |> valueFunction
            member this.sandyBrown = Color.sandyBrown |> valueFunction
            member this.seaGreen = Color.seaGreen |> valueFunction
            member this.seaShell = Color.seaShell |> valueFunction
            member this.sienna = Color.sienna |> valueFunction
            member this.skyBlue = Color.skyBlue |> valueFunction
            member this.slateBlue = Color.slateBlue |> valueFunction
            member this.slateGray = Color.slateGray |> valueFunction
            member this.snow = Color.snow |> valueFunction
            member this.springGreen = Color.springGreen |> valueFunction
            member this.steelBlue = Color.steelBlue |> valueFunction
            member this.tan = Color.tan |> valueFunction
            member this.thistle = Color.thistle |> valueFunction
            member this.tomato = Color.tomato |> valueFunction
            member this.turquoise = Color.turquoise |> valueFunction
            member this.violet = Color.violet |> valueFunction
            member this.wheat = Color.wheat |> valueFunction
            member this.whiteSmoke = Color.whiteSmoke |> valueFunction
            member this.yellowGreen = Color.yellowGreen |> valueFunction
            member this.rebeccaPurple = Color.rebeccaPurple |> valueFunction
            member this.transparent = Color.transparent |> valueFunction
            member this.currentColor = Color.currentColor |> valueFunction
            member this.rgb r g b = Color.rgb(r, g, b) |> valueFunction
            member this.rgba r g b a = Color.rgba(r, g, b, a) |> valueFunction
            member this.hex (value: string) = Color.hex value |> valueFunction
            member this.hsl h s l = Color.hsl(h,s,l) |> valueFunction
            member this.hsla h s l a = Color.hsla(h,s,l,a) |> valueFunction

        type ColorClass (valueFunction: IColor -> CssProperty) =
            inherit ColorBase(valueFunction)
            member this.value color = color |> valueFunction
            member this.inherit' = Inherit |> valueFunction
            member this.initial = Initial |> valueFunction
            member this.unset = Unset |> valueFunction

        type ColorAdjust =
            | Economy
            | Exact

          [<AutoOpen>]
        module colorHelpers =
            let internal colorToString (ColorType c) = c
