namespace FssTypes

[<AutoOpen>]
module CssColor =
   type CssColor =
    | CssColor of string
    interface ITextDecorationColor
    interface ITextEmphasisColor
    interface IBorderColor
    interface IOutlineColor
    interface IColumnRuleColor
    interface ICaretColor
    interface IColorStop
    static member black = Fss.Utilities.Color.hex "000000" |> CssColor
    static member silver = Fss.Utilities.Color.hex "c0c0c0" |> CssColor
    static member gray = Fss.Utilities.Color.hex "808080" |> CssColor
    static member white = Fss.Utilities.Color.hex "ffffff" |> CssColor
    static member maroon = Fss.Utilities.Color.hex "800000" |> CssColor
    static member red = Fss.Utilities.Color.hex "ff0000" |> CssColor
    static member purple = Fss.Utilities.Color.hex "800080" |> CssColor
    static member fuchsia = Fss.Utilities.Color.hex "ff00ff" |> CssColor
    static member green = Fss.Utilities.Color.hex "008000" |> CssColor
    static member lime = Fss.Utilities.Color.hex "00ff00" |> CssColor
    static member olive = Fss.Utilities.Color.hex "808000" |> CssColor
    static member yellow = Fss.Utilities.Color.hex "ffff00" |> CssColor
    static member navy = Fss.Utilities.Color.hex "000080" |> CssColor
    static member blue = Fss.Utilities.Color.hex "0000ff" |> CssColor
    static member teal = Fss.Utilities.Color.hex "008080" |> CssColor
    static member aqua = Fss.Utilities.Color.hex "00ffff" |> CssColor
    static member orange = Fss.Utilities.Color.hex "ffa500" |> CssColor
    static member aliceBlue = Fss.Utilities.Color.hex "f0f8ff" |> CssColor
    static member antiqueWhite = Fss.Utilities.Color.hex "faebd7" |> CssColor
    static member aquaMarine = Fss.Utilities.Color.hex "7fffd4" |> CssColor
    static member azure = Fss.Utilities.Color.hex "f0ffff" |> CssColor
    static member beige = Fss.Utilities.Color.hex "f5f5dc" |> CssColor
    static member bisque = Fss.Utilities.Color.hex "ffe4c4" |> CssColor
    static member blanchedAlmond = Fss.Utilities.Color.hex "ffebcd" |> CssColor
    static member blueViolet = Fss.Utilities.Color.hex "8a2be2" |> CssColor
    static member brown = Fss.Utilities.Color.hex "a52a2a" |> CssColor
    static member burlywood = Fss.Utilities.Color.hex "deb887" |> CssColor
    static member cadetBlue = Fss.Utilities.Color.hex "5f9ea0" |> CssColor
    static member chartreuse = Fss.Utilities.Color.hex "7fff00" |> CssColor
    static member chocolate = Fss.Utilities.Color.hex "d2691e" |> CssColor
    static member coral = Fss.Utilities.Color.hex "ff7f50" |> CssColor
    static member cornflowerBlue = Fss.Utilities.Color.hex "6495ed" |> CssColor
    static member cornsilk = Fss.Utilities.Color.hex "fff8dc" |> CssColor
    static member crimson = Fss.Utilities.Color.hex "dc143c" |> CssColor
    static member cyan = Fss.Utilities.Color.hex "00ffff" |> CssColor
    static member darkBlue = Fss.Utilities.Color.hex "00008b" |> CssColor
    static member darkCyan = Fss.Utilities.Color.hex "008b8b" |> CssColor
    static member darkGoldenrod = Fss.Utilities.Color.hex "b8860b" |> CssColor
    static member darkGray = Fss.Utilities.Color.hex "a9a9a9" |> CssColor
    static member darkGreen = Fss.Utilities.Color.hex "006400" |> CssColor
    static member darkKhaki = Fss.Utilities.Color.hex "bdb76b" |> CssColor
    static member darkMagenta = Fss.Utilities.Color.hex "8b008b" |> CssColor
    static member darkOliveGreen = Fss.Utilities.Color.hex "556b2f" |> CssColor
    static member darkOrange = Fss.Utilities.Color.hex "ff8c00" |> CssColor
    static member darkOrchid = Fss.Utilities.Color.hex "9932cc" |> CssColor
    static member darkRed = Fss.Utilities.Color.hex "8b0000" |> CssColor
    static member darkSalmon = Fss.Utilities.Color.hex "e9967a" |> CssColor
    static member darkSeaGreen = Fss.Utilities.Color.hex "8fbc8f" |> CssColor
    static member darkSlateBlue = Fss.Utilities.Color.hex "483d8b" |> CssColor
    static member darkSlateGray = Fss.Utilities.Color.hex "2f4f4f" |> CssColor
    static member darkTurquoise = Fss.Utilities.Color.hex "00ced1" |> CssColor
    static member darkViolet = Fss.Utilities.Color.hex "9400d3" |> CssColor
    static member deepPink = Fss.Utilities.Color.hex "ff1493" |> CssColor
    static member deepSkyBlue = Fss.Utilities.Color.hex "00bfff" |> CssColor
    static member dimGrey = Fss.Utilities.Color.hex "696969" |> CssColor
    static member dodgerBlue = Fss.Utilities.Color.hex "1e90ff" |> CssColor
    static member fireBrick = Fss.Utilities.Color.hex "b22222" |> CssColor
    static member floralWhite = Fss.Utilities.Color.hex "fffaf0" |> CssColor
    static member forestGreen = Fss.Utilities.Color.hex "228b22" |> CssColor
    static member gainsboro = Fss.Utilities.Color.hex "dcdcdc" |> CssColor
    static member ghostWhite = Fss.Utilities.Color.hex "f8f8ff" |> CssColor
    static member gold = Fss.Utilities.Color.hex "ffd700" |> CssColor
    static member goldenrod = Fss.Utilities.Color.hex "daa520" |> CssColor
    static member greenYellow = Fss.Utilities.Color.hex "adff2f" |> CssColor
    static member grey = Fss.Utilities.Color.hex "808080" |> CssColor
    static member honeydew = Fss.Utilities.Color.hex "f0fff0" |> CssColor
    static member hotPink = Fss.Utilities.Color.hex "ff69b4" |> CssColor
    static member indianRed = Fss.Utilities.Color.hex "cd5c5c" |> CssColor
    static member indigo = Fss.Utilities.Color.hex "4b0082" |> CssColor
    static member ivory = Fss.Utilities.Color.hex "fffff0" |> CssColor
    static member khaki = Fss.Utilities.Color.hex "f0e68c" |> CssColor
    static member lavender = Fss.Utilities.Color.hex "e6e6fa" |> CssColor
    static member lavenderBlush = Fss.Utilities.Color.hex "fff0f5" |> CssColor
    static member lawnGreen = Fss.Utilities.Color.hex "7cfc00" |> CssColor
    static member lemonChiffon = Fss.Utilities.Color.hex "fffacd" |> CssColor
    static member lightBlue = Fss.Utilities.Color.hex "add8e6" |> CssColor
    static member lightCoral = Fss.Utilities.Color.hex "f08080" |> CssColor
    static member lightCyan = Fss.Utilities.Color.hex "e0ffff" |> CssColor
    static member lightGoldenrodYellow = Fss.Utilities.Color.hex "fafad2" |> CssColor
    static member lightGray = Fss.Utilities.Color.hex "d3d3d3" |> CssColor
    static member lightGreen = Fss.Utilities.Color.hex "90ee90" |> CssColor
    static member lightGrey = Fss.Utilities.Color.hex "d3d3d3" |> CssColor
    static member lightPink = Fss.Utilities.Color.hex "ffb6c1" |> CssColor
    static member lightSalmon = Fss.Utilities.Color.hex "ffa07a" |> CssColor
    static member lightSeaGreen = Fss.Utilities.Color.hex "20b2aa" |> CssColor
    static member lightSkyBlue = Fss.Utilities.Color.hex "87cefa" |> CssColor
    static member lightSlateGrey = Fss.Utilities.Color.hex "778899" |> CssColor
    static member lightSteelBlue = Fss.Utilities.Color.hex "b0c4de" |> CssColor
    static member lightYellow = Fss.Utilities.Color.hex "ffffe0" |> CssColor
    static member limeGreen = Fss.Utilities.Color.hex "32cd32" |> CssColor
    static member linen = Fss.Utilities.Color.hex "faf0e6" |> CssColor
    static member magenta = Fss.Utilities.Color.hex "ff00ff" |> CssColor
    static member mediumAquamarine = Fss.Utilities.Color.hex "66cdaa" |> CssColor
    static member mediumBlue = Fss.Utilities.Color.hex "0000cd" |> CssColor
    static member mediumOrchid = Fss.Utilities.Color.hex "ba55d3" |> CssColor
    static member mediumPurple = Fss.Utilities.Color.hex "9370db" |> CssColor
    static member mediumSeaGreen = Fss.Utilities.Color.hex "3cb371" |> CssColor
    static member mediumSlateBlue = Fss.Utilities.Color.hex "7b68ee" |> CssColor
    static member mediumSpringGreen = Fss.Utilities.Color.hex "00fa9a" |> CssColor
    static member mediumTurquoise = Fss.Utilities.Color.hex "48d1cc" |> CssColor
    static member mediumVioletRed = Fss.Utilities.Color.hex "c71585" |> CssColor
    static member midnightBlue = Fss.Utilities.Color.hex "191970" |> CssColor
    static member mintCream = Fss.Utilities.Color.hex "f5fffa" |> CssColor
    static member mistyRose = Fss.Utilities.Color.hex "ffe4e1" |> CssColor
    static member moccasin = Fss.Utilities.Color.hex "ffe4b5" |> CssColor
    static member navajoWhite = Fss.Utilities.Color.hex "ffdead" |> CssColor
    static member oldLace = Fss.Utilities.Color.hex "fdf5e6" |> CssColor
    static member olivedrab = Fss.Utilities.Color.hex "6b8e23" |> CssColor
    static member orangeRed = Fss.Utilities.Color.hex "ff4500" |> CssColor
    static member orchid = Fss.Utilities.Color.hex "da70d6" |> CssColor
    static member paleGoldenrod = Fss.Utilities.Color.hex "eee8aa" |> CssColor
    static member paleGreen = Fss.Utilities.Color.hex "98fb98" |> CssColor
    static member paleTurquoise = Fss.Utilities.Color.hex "afeeee" |> CssColor
    static member paleVioletred = Fss.Utilities.Color.hex "db7093" |> CssColor
    static member papayaWhip = Fss.Utilities.Color.hex "ffefd5" |> CssColor
    static member peachpuff = Fss.Utilities.Color.hex "ffdab9" |> CssColor
    static member peru = Fss.Utilities.Color.hex "cd853f" |> CssColor
    static member pink = Fss.Utilities.Color.hex "ffc0cb" |> CssColor
    static member plum = Fss.Utilities.Color.hex "dda0dd" |> CssColor
    static member powderBlue = Fss.Utilities.Color.hex "b0e0e6" |> CssColor
    static member rosyBrown = Fss.Utilities.Color.hex "bc8f8f" |> CssColor
    static member royalBlue = Fss.Utilities.Color.hex "4169e1" |> CssColor
    static member saddleBrown = Fss.Utilities.Color.hex "8b4513" |> CssColor
    static member salmon = Fss.Utilities.Color.hex "fa8072" |> CssColor
    static member sandyBrown = Fss.Utilities.Color.hex "f4a460" |> CssColor
    static member seaGreen = Fss.Utilities.Color.hex "2e8b57" |> CssColor
    static member seaShell = Fss.Utilities.Color.hex "fff5ee" |> CssColor
    static member sienna = Fss.Utilities.Color.hex "a0522d" |> CssColor
    static member skyBlue = Fss.Utilities.Color.hex "87ceeb" |> CssColor
    static member slateBlue = Fss.Utilities.Color.hex "6a5acd" |> CssColor
    static member slateGray = Fss.Utilities.Color.hex "708090" |> CssColor
    static member snow = Fss.Utilities.Color.hex "fffafa" |> CssColor
    static member springGreen = Fss.Utilities.Color.hex "00ff7f" |> CssColor
    static member steelBlue = Fss.Utilities.Color.hex "4682b4" |> CssColor
    static member tan = Fss.Utilities.Color.hex "d2b48c" |> CssColor
    static member thistle = Fss.Utilities.Color.hex "d8bfd8" |> CssColor
    static member tomato = Fss.Utilities.Color.hex "ff6347" |> CssColor
    static member turquoise = Fss.Utilities.Color.hex "40e0d0" |> CssColor
    static member violet = Fss.Utilities.Color.hex "ee82ee" |> CssColor
    static member wheat = Fss.Utilities.Color.hex "f5deb3" |> CssColor
    static member whiteSmoke = Fss.Utilities.Color.hex "f5f5f5" |> CssColor
    static member yellowGreen = Fss.Utilities.Color.hex "9acd32" |> CssColor
    static member rebeccaPurple = Fss.Utilities.Color.hex "663399" |> CssColor
    static member transparent = Fss.Utilities.Color.rgba 0 0 0 0.0 |> CssColor
    static member currentColor = "currentColor" |> CssColor
    static member Rgb (r: int, g: int, b: int) = Fss.Utilities.Color.rgb r g b |> CssColor
    static member Rgba (r: int, g: int, b: int, a: float) = Fss.Utilities.Color.rgba r g b a |> CssColor
    static member Hex (value: string) = Fss.Utilities.Color.hex value |> CssColor
    static member Hsl (h: int, s: float, l: float) = Fss.Utilities.Color.hsl h s l |> CssColor
    static member Hsla (h: int, s: float, l: float, a: float) = Fss.Utilities.Color.hsla h s l a |> CssColor

module CssColorValue =
    open CssColor
    let color (CssColor c) = c