// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Feliz.UseListener")>]
[<assembly: AssemblyProductAttribute("Feliz.UseListener")>]
[<assembly: AssemblyDescriptionAttribute("React hook for easy event listener management.")>]
[<assembly: AssemblyVersionAttribute("0.6.3")>]
[<assembly: AssemblyFileVersionAttribute("0.6.3")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Feliz.UseListener.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Feliz.UseListener"
    let [<Literal>] AssemblyProduct = "Feliz.UseListener"
    let [<Literal>] AssemblyDescription = "React hook for easy event listener management."
    let [<Literal>] AssemblyVersion = "0.6.3"
    let [<Literal>] AssemblyFileVersion = "0.6.3"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Feliz.UseListener.Tests"
