name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Install packages
      run: dotnet restore
    - uses: oven-sh/setup-bun@v2
    - name: Install bun packages
      run: bun install
    - name: Test dotnet
      run: dotnet run --project tests
    - name: Test Fable
      run: bun run test
    - name: Validate CSS
      run: bun run validate